### PR TITLE
feat: add new Setting: Remove check for conflicts

### PR DESCRIPTION
**Pull request by maicol07**
This PR introduces a new setting that removes the check for conflicts when creating a new booking.

Example:

Let's take this scenario: a booking with enter time 9:00 and leave time 13:00 already exists. I want to book the time slot 13:00-18:00.

Although this would be logically fine, the app won't allow it because it checks if the new time slot is between the other bookings time slots. So, this new setting allows to override this behaviour by removing the check for enter time equal to the new booking leave time and vice versa.

Also the scenario where the new enter time is equal to the enter time of the already existing booking is supported (i.e. 8:00-9:00)

### CODE REVIEW

**Comment by virtualzone** [comment]
Thanks for identifying this issue!
Does this really require a new setting, or should be better improve the conflict-checking-logic so that non-overlapping slots (like end = 13:00 and start = 13:00) get accepted?

**Comment by maicol07** [comment]
I don't know, I've added a setting to keep the old behaviour and not do a breaking change (I don't know if someone uses this as a feature, although it's more like a bug)

**Comment by virtualzone** [comment]
I guess the behaviour you endorse with this PR should be the default. Therefore I released the conflict checking in PR #296.

**Comment by maicol07** [comment]
Great! I think this can be closed now

**Pull request closed without merging**
